In [86]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import svm
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate

In [75]:
knearestdata = pd.read_csv("breast-cancer-wisconsin.data")
knearestdata.head()
knearestdata.describe()
knearestdata.replace('?',-99999,inplace=True)
X = np.array(knearestdata.drop(['1000025'],1))
y = np.array(knearestdata['1000025'])
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.33, random_state=101)
clf = KNeighborsClassifier()
clf.fit(X_train,Y_train)
accuracy = clf.score(X_test,Y_test)
print(accuracy)

0.004329004329004329

In [76]:
clf = tree.DecisionTreeClassifier()
clf.fit(X_train,Y_train)
accuracy1 = clf.score(X_test,Y_test)
print(accuracy1)

0.004329004329004329

In [77]:
clf = svm.SVC(kernel='linear')
clf.fit(X_train,Y_train)
accuracy = clf.score(X_test,Y_test)
print(accuracy)

0.008658008658008658

In [85]:
clf = LogisticRegression(solver='liblinear')
clf.fit(X_train,Y_train)
accuracy = clf.predict(X_test,Y_test)
print(accuracy)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

TypeError: predict() takes 2 positional arguments but 3 were given

In [95]:
knearestdata.rename(columns = {'1000025':'id'}, inplace=True)

In [96]:
knearestdata

          id   5   1  1.1  1.2  2     1.3   3  1.4  1.5  2.1
0    1002945   5   4    4    5  7      10   3    2    1    2
1    1015425   3   1    1    1  2       2   3    1    1    2
2    1016277   6   8    8    1  3       4   3    7    1    2
3    1017023   4   1    1    3  2       1   3    1    1    2
4    1017122   8  10   10    8  7      10   9    7    1    4
5    1018099   1   1    1    1  2      10   3    1    1    2
6    1018561   2   1    2    1  2       1   3    1    1    2
7    1033078   2   1    1    1  2       1   1    1    5    2
8    1033078   4   2    1    1  2       1   2    1    1    2
9    1035283   1   1    1    1  1       1   3    1    1    2
10   1036172   2   1    1    1  2       1   2    1    1    2
11   1041801   5   3    3    3  2       3   4    4    1    4
12   1043999   1   1    1    1  2       3   3    1    1    2
13   1044572   8   7    5   10  7       9   5    5    4    4
14   1047630   7   4    6    4  6       1   4    3    1    4
15   1048672   4   1    1    1  2       1   2    1    1    2
16   1049815   4   1    1    1  2       1   3    1    1    2
17   1050670  10   7    7    6  4      10   4    1    2    4
18   1050718   6   1    1    1  2       1   3    1    1    2
19   1054590   7   3    2   10  5      10   5    4    4    4
20   1054593  10   5    5    3  6       7   7   10    1    4
21   1056784   3   1    1    1  2       1   2    1    1    2
22   1057013   8   4    5    1  2  -99999   7    3    1    4
23   1059552   1   1    1    1  2       1   3    1    1    2
24   1065726   5   2    3    4  2       7   3    6    1    4
25   1066373   3   2    1    1  1       1   2    1    1    2
26   1066979   5   1    1    1  2       1   2    1    1    2
27   1067444   2   1    1    1  2       1   2    1    1    2
28   1070935   1   1    3    1  2       1   1    1    1    2
29   1070935   3   1    1    1  1       1   2    1    1    2
..       ...  ..  ..  ...  ... ..     ...  ..  ...  ...  ...
668  1350423   5  10   10    8  5       5   7   10    1    4
669  1352848   3  10    7    8  5       8   7    4    1    4
670  1353092   3   2    1    2  2       1   3    1    1    2
671  1354840   2   1    1    1  2       1   3    1    1    2
672  1354840   5   3    2    1  3       1   1    1    1    2
673  1355260   1   1    1    1  2       1   2    1    1    2
674  1365075   4   1    4    1  2       1   1    1    1    2
675  1365328   1   1    2    1  2       1   2    1    1    2
676  1368267   5   1    1    1  2       1   1    1    1    2
677  1368273   1   1    1    1  2       1   1    1    1    2
678  1368882   2   1    1    1  2       1   1    1    1    2
679  1369821  10  10   10   10  5      10  10   10    7    4
680  1371026   5  10   10   10  4      10   5    6    3    4
681  1371920   5   1    1    1  2       1   3    2    1    2
682   466906   1   1    1    1  2       1   1    1    1    2
683   466906   1   1    1    1  2       1   1    1    1    2
684   534555   1   1    1    1  2       1   1    1    1    2
685   536708   1   1    1    1  2       1   1    1    1    2
686   566346   3   1    1    1  2       1   2    3    1    2
687   603148   4   1    1    1  2       1   1    1    1    2
688   654546   1   1    1    1  2       1   1    1    8    2
689   654546   1   1    1    3  2       1   1    1    1    2
690   695091   5  10   10    5  4       5   4    4    1    4
691   714039   3   1    1    1  2       1   1    1    1    2
692   763235   3   1    1    1  2       1   2    1    2    2
693   776715   3   1    1    1  3       2   1    1    1    2
694   841769   2   1    1    1  2       1   1    1    1    2
695   888820   5  10   10    3  7       3   8   10    2    4
696   897471   4   8    6    4  3       4  10    6    1    4
697   897471   4   8    8    5  4       5  10    4    1    4

[698 rows x 11 columns]